/**
 * @file config.hpp
 * @brief Library configuration, feature detection, and API export macros
 *
 * This is the single entry point for all libgossip compile-time configuration.
 * It provides:
 * - API export/import macros (replaces the old libgossip_api.h)
 * - Logging control
 * - Debug/assertion macros
 * - Default configuration constants
 * - Platform/compiler/architecture detection
 *
 * @note Include this header wherever you need LIBGOSSIP_API or configuration values.
 */

#pragma once

#include "libgossip_api.h"
#include <cstdint>
#include <cstddef>

// ============================================
// Version Information (generated by CMake)
// ============================================
#include <core/version.hpp>

// ============================================
// Feature Flags
// ============================================

// Enable verbose logging (controlled by CMake or user)
#ifndef LIBGOSSIP_ENABLE_LOGGING
    #define LIBGOSSIP_ENABLE_LOGGING 1
#endif

// Enable assertions (enabled in debug builds by default)
#ifndef LIBGOSSIP_ENABLE_ASSERTIONS
    #ifdef NDEBUG
        #define LIBGOSSIP_ENABLE_ASSERTIONS 0
    #else
        #define LIBGOSSIP_ENABLE_ASSERTIONS 1
    #endif
#endif

// ============================================
// Configuration Constants
// ============================================

namespace libgossip::config {

// Gossip Protocol Configuration
constexpr uint32_t DEFAULT_HEARTBEAT_INTERVAL_MS = 100;
constexpr uint32_t DEFAULT_FAILURE_TIMEOUT_MS = 2000;
constexpr uint32_t DEFAULT_GOSSIP_NODES = 3;
constexpr uint32_t DEFAULT_SYNC_NODES = 2;

// Network Configuration
constexpr size_t DEFAULT_TCP_RECV_BUFFER_SIZE = 65536;
constexpr size_t DEFAULT_UDP_RECV_BUFFER_SIZE = 65536;
constexpr size_t DEFAULT_MAX_MESSAGE_SIZE = 1024 * 1024; // 1MB

// Node Configuration
constexpr size_t DEFAULT_MAX_NODES = 1000;
constexpr size_t DEFAULT_NODE_METADATA_SIZE_LIMIT = 65536; // 64KB

} // namespace libgossip::config

// ============================================
// Compiler Detection
// ============================================

#if defined(_MSC_VER)
    #define LIBGOSSIP_COMPILER_MSVC _MSC_VER
#elif defined(__clang__)
    #define LIBGOSSIP_COMPILER_CLANG (__clang_major__ * 10000 + __clang_minor__ * 100 + __clang_patchlevel__)
#elif defined(__GNUC__)
    #define LIBGOSSIP_COMPILER_GCC (__GNUC__ * 10000 + __GNUC_MINOR__ * 100 + __GNUC_PATCHLEVEL__)
#endif

// ============================================
// Utility Macros
// ============================================

// Mark a variable as unused
#define LIBGOSSIP_UNUSED(x) (void)(x)

// Compile-time assertion
#define LIBGOSSIP_STATIC_ASSERT(cond, msg) static_assert(cond, msg)

// Runtime assertion (only in debug builds)
#if LIBGOSSIP_ENABLE_ASSERTIONS
    #define LIBGOSSIP_ASSERT(cond) \
        do { \
            if (!(cond)) { \
                std::fprintf(stderr, "Assertion failed: %s at %s:%d\n", \
                            #cond, __FILE__, __LINE__); \
                std::abort(); \
            } \
        } while(0)
#else
    #define LIBGOSSIP_ASSERT(cond) ((void)0)
#endif

// Logging macros (actual implementation in logger.hpp)
#if LIBGOSSIP_ENABLE_LOGGING
    #define LIBGOSSIP_LOG(level, message) \
        do { \
            std::stringstream ss; \
            ss << message; \
            libgossip::Logger::Instance().Log(libgossip::LogLevel::level, ss.str()); \
        } while(0)
#else
    #define LIBGOSSIP_LOG(level, message) ((void)0)
#endif

#define LIBGOSSIP_LOG_TRACE(msg) LIBGOSSIP_LOG(TRACE, msg)
#define LIBGOSSIP_LOG_DEBUG(msg) LIBGOSSIP_LOG(DEBUG, msg)
#define LIBGOSSIP_LOG_INFO(msg)  LIBGOSSIP_LOG(INFO,  msg)
#define LIBGOSSIP_LOG_WARN(msg)  LIBGOSSIP_LOG(WARN,  msg)
#define LIBGOSSIP_LOG_ERROR(msg) LIBGOSSIP_LOG(ERROR, msg)
#define LIBGOSSIP_LOG_FATAL(msg) LIBGOSSIP_LOG(FATAL, msg)
